emp:
  service:
      url: "http://localhost:8080/"
cloudConfig:
   mysql:
     url: "jdbc:mysql://localhost:3306/inventory"
     username: "root"
     password: ""
     driverClassName: "com.mysql.cj.jdbc.Driver"
